### ISSUE TITLE
usb_blink_pc -pc not implemented

### ISSUE THREAD

**Issue by nerdralph** [ole00/ch554_sdcc_usb_blinky#3]
`arvic-usb: fatal: unknown parameter: -pc`
I looked at the source and confirmed it is not implmented.

I'd also suggest printing argv[0] instead of 'arvic-usb'.

**Comment by ole00** [comment]
Thanks. These were leftovers from an old project. Now cleaned.

argv[0] : good suggestion, but the argv not available everywhere in the code, so I'd have to do more changes (which I'm lazy to do :--)

**Comment by nerdralph** [comment]
I see you removed the -pc option from the options list.  Looks good.
